site_name: Found.Soft.Sci
nav:
    - Home: index.md
    - Notes: 
         - Admin:
              - Syllabus : syllabus.md
              - Submit site: http://tiny.cc/fss18give
              - Chat: http://found18.slack
         - Baselines for Adequate AI: lectures/baselines.md
         - Starting:
             - Inspiration : inspiration.md
             - SE+AI,  then and now: history.md
    - H/W: 
         - One: proj/w1.md 
         - Review: 
             - Week2: review/w2.md
             - Week1: review/w1.md
    - A-Z: 
         - E: 
              - Effect size: lectures/effectsize.md
              - Explanation: lectures/explain.md
         - B: 
              - Bootstrap: lectures/bootstrap.md
         - S:
              - Significance test: lectures/significance.md 
              - Simplicity: lectures/simple.md
              - Scott-Knot: lectures/sk.md
         - T:
              - Tables : lectures/tables.md
              - Things : lectures/things.md
              - Tools:
                 - Data mining:
                      - Matlab : aa
                      - R : bb
                      - Weka : cc
                      - scikit-learn : dd
                 - Optimizers:
                      - JMetal: dd
                      - Deep: dd
                      - EvoSuite: ee
    - (c) 2018 Tim Menzies: license.md
extra_css:
    - css/extra.css
edit_uri: tree/master/web/docs
repo_url: http://github.com/txt/fss18
