site_name: ncsu/cs/fss/2018
nav:
    - Home: index.md
    - Notes: 
         - Syllabus : syllabus.md
         - Bye: lectures/w2.md
         - Bad Smells for AI : lectures/baselines.md
         - Starting:
             - Hello : index.md
             - Inspiration : inspiration.md
             - SE+AI,  then and now: history.md
    - H/W: 
         - One: proj/w1.md

    - Review: 
         - Week1: review/w2.md
         - Week1: review/w1.md
    - Terms: 
         - E: 
              - Effect size: gloss/effectsize.md
         - B: 
              - Bootstrap: gloss/bootstrap.md
         - S:
              - Significance test: gloss/significance.md 
              - Scott-Knot: gloss/sk.md
    - License: license.md
extra_css:
    - css/extra.css
edit_uri: tree/master/web/docs
repo_url: http://github.com/txt/fss18
