site_name: Found.Soft.Sci
nav:
    - Home: index.md
    - Notes: 
         - Admin:
              - Syllabus &#10004;: syllabus.md
              - Submit site &#10004;: http://tiny.cc/fss18give
              - Chat &#10004;: http://found18.slack.com
         - Starting:
             - Inspiration &#10004; : inspiration.md
             - SE+AI,  then and now &#10004;: history.md
             - Baselines for Adequate AI &#10004; : lectures/baselines.md
             - Simplicity ; : lectures/simple.md 
         - Lectures:
             - Tables and Ranges &#10004:  lectures/tables.md
             - Decision trees 101 &#10004:  lectures/dt101.md
    - H/W: 
         - Project Ideas: proj/ProjectIdeas 
         - Four &#10004;: proj/w4.md 
         - Three &#10004;: proj/w3.md 
         - One &#10004;: proj/w1.md 
         - Review: 
             - Week2: review/w2.md
             - Week1 &#10004; : review/one.md
    - A-Z: 
         - A: 
              - Axe: lectures/axe.md
         - D: 
              - Deep learning &#10004;: lectures/deeplearning.md
         - E: 
              - Effect size: lectures/effectsize.md
              - Explanation: lectures/explain.md
         - B: 
              - Bootstrap: lectures/bootstrap.md
         - S:
              - Significance test: lectures/significance.md 
              - Scott-Knot: lectures/sk.md
         - T:
              - Tables : lectures/tables.md
              - Things : lectures/things.md
              - Tools:
                 - Data mining:
                      - Matlab : aa
                      - R : bb
                      - Weka : cc
                      - scikit-learn : dd
                 - Optimizers:
                      - JMetal: dd
                      - Deep: dd
                      - EvoSuite: ee
    - (c) 2018: license.md
extra_css:
    - css/extra.css
